export default {
  clientNav: {
    home: 'Басты',
    notes: 'Ескертпелер',
    photos: 'Фотосүйреттер',
    statistic: 'Статистика',
    questionnaire: 'Сауалнама',
    faq: 'Қосымша материалдар',
    additional: 'Қосымша',
    help: 'Көмектесіңдер'
  },
  headerAccount: {
   settings: 'Параметрлер',
   language: 'Тіл',
   exit: 'Шығу'
  },
  trainerNav: {
   clients: 'Клиенттер',
   clientsMessages: 'Клиенттерден келген хабарламалар',
  },
  historyIntroductions: {
   welcome: 'Қош келдіңіз',
   historyTitle: '1. Тарих',
   subtitle: 'Сіз үшін жеке оқу бағдарламасын бейімдеу үшін біз бұл туралы көбірек білуіміз керек \
   сіз және сіздің проблемаңыз. туралы сұрақтарға жауап беру \
   сіздің ауырсынуыңыз, қозғалу қабілетіңіз және позаңыз. \
   Сіздің жаттығу бағдарламаңыз бірден қолжетімді болады, \
   сауалнаманы толтырғаннан кейін',
   oferta1: 'Мен шарттарды оқыдым және қабылдаймын',
   oferta2: 'Келісімшарттық ұсыныстар ',
   oferta3: 'Және',
   oferta4: 'Құпиялылық саясаты ',
   oferta5: '.',
   continueBtn: 'Жалғастыру',
   startBtn: 'Бастау'
  },
  historyPainInfo: {
   title: 'Ауырсыну туралы ақпарат ',
   subtitle: 'Ауырсыну орындарын көрсетіңіз ',
   painPlace: 'Ауырсыну орындары',
   painPlaceShort: 'Ол қай жерде ауырады?',
   painPlaceItem1: 'Мойын',
   painPlaceItem2: 'Жамбас',
   painPlaceItem3: 'Иық',
   painPlaceItem4: 'Кеуде арқасы',
   painPlaceItem5: 'Тізе',
   painPlaceItem6: 'Қол',
   painPlaceItem7: 'Бел',
   painPlaceItem8: 'Табан',
   painChoiceTitle: 'Ең көп ауыратын бір жерді таңдаңыз ',
   painNumberTitle: '0-ден 10-ға дейін қаншалықты ауырады (0 ауыртпайды, 10 қатты ауырады)',
   painPlaceError: 'Ауырсыну орнын көрсетіңіз',
   painNubmerError: 'Ауырсыну күшін көрсетіңіз',
   painTime: 'Қашаннан бері ауырып жүрсіз?',
   painTimeShort: 'Бұл ауырсыну сізді қашаннан бері мазалайды?',
painTimePlaceholder1: 'Жыл',
   painTimePlaceholder2: 'Ай',
   painTimePlaceholder3: 'Күн',
   painTimeError: 'Бұл ауруды қанша уақыттан бері сезінгеніңізді көрсетіңіз ',
   painWhenTime: 'Ауырсыну сізді мазалаған кезді көрсетіңіз ',
   paintWhenTimeShort: 'Қай кезде ауырсыну сізді қатты мазалайды?',
   painWhenTimeError: 'Ауырсыну қашан пайда болғанын көрсетіңіз',
   painWhenTimePlaceholder1: 'Таңертең оянғаннан кейін',
   painWhenTimePlaceholder2: 'Күннің соңында ',
   painWhenTimePlaceholder3: 'Жаттығудан кейін',
   painWhenTimePlaceholder4: 'Ұзақ отырған соң',
   painWhenTimePlaceholder5: 'Ауыр көтергеннен кейін',
   painWhenTimePlaceholder6: 'Әрқашан',
   painWhenTimePlaceholder7: 'Басқа...',
   diagnosisTitle: 'Какой вам ставили диагноз? (если ставили)',
   painAdd: 'Сіздің диагнозыңыз қандай болды? (орнатылған болса)',
   painAddShort: 'Басқа жеріңіз ауырады ма? ',
   painAddShortAnswer1: 'Иә',
   painAddShortAnswer2: 'Жоқ',
   painDelete: 'Қосымша ауырсыну орнын алып тастаңыз',
painAdditional: 'Сіз хабарлағыңыз келетін басқа ауырсынуларыңыз бар ма?',
   treatmentsTitle: 'Сіз қолданып көрген емдеу әдістерін көрсетіңіз',
   treatmentsTitleShort: 'Сіз қандай емдерді қолдандыңыз?',
   treatmentsPlaceholder1: 'Қолмен терапия ',
   treatmentsPlaceholder2: 'Физиотерапия',
   treatmentsPlaceholder3: 'Ота жасату',
   treatmentsPlaceholder4: 'Ауырсынуды басатын дәрі',
   treatmentsPlaceholder5: 'Иглотерапия',
   treatmentsPlaceholder6: 'Кеудетерапия',
   treatmentsPlaceholder7: 'ЛФК',
   treatmentsPlaceholder8: 'Йога, пилатесс',
   treatmentsPlaceholder9: 'Тартым',
   treatmentsPlaceholder10: 'Басқа...',
   treatmentsError: 'Қандай емдерді қолданып көргеніңізді көрсетіңіз',
   continueBtn: 'Жалғастыру',
  },
  historyYourCondition: {
   title: 'Сіздің жағдайыңыз',
   subtitle: 'Енді жағдайыңызды бағалаңыз',
   conditionTitle: 'Жалпы жағдайыңыз',
   conditionSubtitle: 'Жалпы физикалық жағдайыңызды 0-ден 100%-ға дейінгі шкала бойынша бағалаңыз',
   conditionPlaceholder: 'Жалпы физикалық жағдайыңызды сипаттаңыз',
   conditionError: 'Жалпы жағдайыңызды көрсетіңіз',
energyTitle: 'Энергия',
   energySubtitle: 'Орташа энергия деңгейіңізді 0-ден 100%-ға дейінгі шкала бойынша бағалаңыз',
   energyPlaceholder: 'Жалпы энергия деңгейіңізді сипаттаңыз',
   energyError: 'Энергия күйіңізді көрсетіңіз',
   sleepTitle: 'Ұйқы',
   sleepSubtitle: 'Ұйқының орташа сапасын 0-ден 100%-ға дейінгі шкала бойынша бағалаңыз',
   sleepPlaceholder: 'Ұйқыңыздың сапасын сипаттаңыз',
   sleepError: 'Ұйқының сапасын көрсетіңіз',
   continueBtn: 'Жалғастыру',
  },
  historyYourInfo: {
   title: 'Сіз туралы ақпарат ',
   subtitle: 'Енді бір-бірімізді аздап білуіміз керек. Сіз туралы маңызды ақпаратты енгізіңіз ',
   sexTitle: 'Жыныс',
   sexItem1: 'Еркек',
   sexItem2: 'Әйел',
   sexError: 'Жынысты таңдаңыз',
   birthTitle: 'Туған күн',
   birthError: 'Туылған күніңізді белгілеңіз ',
   heightWeightTitle: 'Бой / Салмақ',
   heightWeightPlaceholder1: 'Бой',
   heightWeightPlaceholder2: 'Салмақ',
   heightWeightError: 'Бойыңыз бен салмағыңызды енгізіңіз ',
   workTitle: 'Сіз немен айналысасыз?',
   workSubtitle: 'Бұл сіздің қаншалықты қозғалғаныңызды түсінуге көмектеседі',
   workItem1: 'Кәсіпкер',
   workItem2: 'Үй шаруасындағы әйел ',
   workItem3: 'Жүргізуші',
   workItem4: 'Фрилансер',
   workItem5: 'Студент',
   workItem6: 'Бағдарламашы',
   workItem7: 'Кеңсе қызметкері ',
   workItem8: 'Мұғалім',
   workItem9: 'Зейнеткер',
   workItem10: 'Басқа...',
   workError: 'Мамандықты көрсетіңіз ',
   continueBtn: 'Жалғастыру',
},
  mobilityIntroductions: {
   title: 'Нұсқау',
   mobilityTitle: '2. Ұтқырлық',
   subtitle: 'Әрі қарай, біз сіздің моторикаңызды жақсы түсінуіміз керек. \
   қабілеттерін және сізбен бірге бірнеше \
   қарапайым функционалдық сынақтар. Бұл сұрақтар \
   ең тиімдісін таңдауға көмектесіңіз \
   Сізге қазіргі пішінде жаттығулар.',
   startBtn: 'Бастау',
   continueBtn: 'Жалғастыру',
  },
  mobilityQuestion: {
   title: 'Сауалнама',
   subtitle: 'Бұл қадамда сіз өзіңіздің моторикаңыз туралы сұрақтарға жауап беруіңіз керек',
   stayTitle: 'Сізге тұру оңай ма? ',
   staySubtitle: 'Сезімдеріңізді білдіріңіз',
   stayItem1: 'Оңай',
   stayItem2: 'Жақсы',
   stayItem3: 'Қиын',
   stayItem4: 'Өте қиын',
   stayError: 'Сізге тұру оңай ма, соны көрсетіңіз ',
   sitTitle: 'Сізге отыру оңай ма?',
   sitSubtitle: 'Сезімдеріңізді білдіріңіз',
   sitItem1: 'Оңай',
   sitItem2: 'Жақсы',
   sitItem3: 'Қиын',
   sitItem4: 'Өте қиын',
   sitError: 'Сізге отыру оңай ма?',
   standupTitle: 'Сізге еденнен тұру оңай ма?',
   standupSubtitle: 'Сезімдеріңізді білдіріңіз',
   standupItem1: 'Оңай',
   standupItem2: 'Жақсы',
   standupItem3: 'Киын',
   standupItem4: 'Өте қиын',
   standupError: 'Сізге еденнен тұру оңай ма?',
   continueBtn: 'Жалғастыру',
  },

mobilityTest: {
   title: 'Сауалнама',
   subtitle: 'Бұл қадамда сіз өзіңіздің моторикаңыз туралы сұрақтарға жауап беруіңіз керек',
   firstTestTitle: 'Функционалдық сынақ #1',
   firstTestSubtitle: 'Сезімдеріңізді білгілеңіз ',
   firstTestQuestionDescription: 'Аяқ киімсіз тұрыңыз . \
   Аяғыңызды біріктіріңіз. \
   Демалыңыз және поза бермеңіз. Көздеріңді жабыңдар .',
   firstTestQuestionDescriptionAdditional: 'Сезімдерің қандай?',
   firstTestQuestionItem1: 'Тұрақтылық пен тепе-теңдік',
   firstTestQuestionItem2: 'Дене құлап немесе теңселіп жатыр ',
   firstTestQuestionItem3: 'Жауап беруге қиналамын',
   firstTestQuestionError: 'Сізге тұру оңай ма, соны көрсетіңіз ',
   secondTestTitle: 'Функционалдық сынақ #2',
   secondTestSubtitle: 'Сезімдеріңізді білгілеңіз',
   secondTestQuestionDescription: 'Аяқтарды біріктіріп, тұрақты күйде болыңыз. \
   Саусақтарыңызды басыңыздың артына айқастырыңыз. \
   Кеудеңізді кеңейту үшін шынтағыңызды мүмкіндігінше артқа тартыңыз. \
   Көзіңді жабыңыз. Сезімдерің өзгерді ме?',
   secondTestQuestionItem1: 'Тұру оңай болды',
   secondTestQuestionItem2: 'Тұру қиындап кетті',
   secondTestQuestionItem3: 'Жауап беруге қиналамын',
   secondTestQuestionError: 'Укажите легко ли вам сидеть',
   trirdTestTitle: 'Функциональный тест #3',
   trirdTestSubtitle: 'Сезімдеріңізді білгілеңіз',
   trirdTestQuestionDescription: 'Аяқ киімсіз тұрыңыз. Бір аяқты көтеріңіз. \
   Сезімдеріңізді тыңдаңыз. Аяқтарды ауыстырып, қайталаңыз. \
   Қандай сезімде болдыңыз? Әр аяққа тұру оңай болды ма?',

trirdTestQuestionItem1: 'Сол жақта оңайырақ ',
   trirdTestQuestionItem2: 'Бірдей оңай ',
   trirdTestQuestionItem3: 'Оң жақта оңайырақ',
   trirdTestQuestionItem4: 'Бірдей қиын',
   trirdTestQuestionItem5: 'Жауап беруге қиналамын',
   trirdTestQuestionError: 'Сізге еденнен тұру оңай ма, соны көрсетіңіз',
   continueBtn: 'Жалғастыру',
  },
  postureFinal: {
   title: 'Соңы',
   subtitle: 'Сауалнаманың сәтті аяқталуымен құттықтаймыз. Енгізілген ақпаратқа сенімді болсаңыз, «Аяқтау» түймесін басыңыз. \
   Одан кейін параметрлерді өзгерте алмайтыныңызды ескеріңіз.',
   endBtn: 'Аяқтау'
  },
  postureIntroductions: {
   title: 'Позаны анықтау',
   postureTitle: '3. Поза',
   error: 'Позаның түрін көрсетіңіз',
   subtitle: 'Позаңыздың фотосуретін бүйірден қараңыз. Жамбастың орналасуына назар аударыңыз. \
   Төмендегі поза түрлерінің қайсысы сіздің денеңізге көбірек ұқсайды? \
   Ең ұқсас нұсқаны таңдаңыз, тіпті ұқсастық 100% болмаса да, бұл сұраққа тоқталмаңыз',
   type1: '1 Түр',
   type2: '2 Түр',
   type3: '3 Түр',
sideError: 'Укажите тип осанки сбоку',
   type1Description: '1 түрі: жамбас алға еңкейтілген. Төменгі арқада айқын ауытқу бар (лордоз). Іші дөңгелек.',
   type2Description: '2 түрі: жамбас артқа қисайтылған. Белі біршама тегіс. Омыртқа S әрпіне қарағанда С әрпіне көбірек ұқсайды. Дененің үстіңгі жағы еңкейген.',
   type3Description: '3-түрі: жамбас аяғы мен иығына қатысты айқын алға қарай. Дене доғаға немесе жақшаға ұқсайды «)»',
   scoliosisTitle: 'Сізде сколиоз бар ма?',
   scoliosisItem1: 'Иә',
   scoliosisItem2: 'Жоқ',
   additionalQuestionDescription1: 'Аяқ киімсіз тұрыңыз. Демалыңыз, поза бермеңіз.',
   additionalQuestionDescription2: 'Денеңізді төмен түсіріп, айнадағы көрініске қараңыз.',
   additionalQuestionDescription3: 'Сіз иығыңызда немесе аяқтарыңызда сәл бұрылысты көресіз бе? Мүмкін бір қол, аяқ немесе жамбас екіншісінің алдында тұрған шығар?', 
additionalQuestionDescription4: 'Аяқтардың бір-біріне қатысты орналасуына назар аударыңыз? Олар бір жолда ма?',
additionalQuestionDescription5: 'Қолдарына қара? Қолдарыңыз бірдей қашықтықта орналасқан ба?',
   spreadsTitle: 'Сіз денеде таралу белгілерін көресіз бе?',
   spreadsItem1: 'Иә',
   spreadsItem2: 'Жоқ',
   startBtn: 'Бастау',
   continueBtn: 'Жалғастыру',
},
  posturePhotos: {
   title: 'Фотосуйрет',
   photosTitle: 'Фотосуреттеріңізді жүктеңіз ',
   photosTitleShort: 'Поза суреттерін жүктеп салу',
   photosSubtitle: 'Фотосуретті жүктеп салу кезінде поза сызығын дәл ортаға қойыңыз',
   showLinesName: 'Жолдарды көрсету',
   addPhoto: 'Фото қосу',
   continueBtn: 'Жалғастыру',
  },
  completeReg: {
   title: 'Аяқтау',
   subtitle: 'Сіздің бірегей жаттығу бағдарламаңыз жасалуда!'
  },
  mzoStatisticalAllDone: {
   title: 'Бәрі дайын!',
   subtitle1: 'Жауаптарыңызға рахмет!',
   subtitle2: 'Біз жаттығу бағдарламасын сіздің жағдайыңызға сәйкес келтіруді жалғастырамыз',
   continueBtn: 'Жалғастыру',
  },
  mzoStatisticalCongratulations: {
   title: 'Құттықтаймыз,',
   subtitle1: 'Сіз күнді аяқтадыңыз',
   subtitle2: 'MЗО бағдарламасының апталығы!',
   description: 'Үзіліс жасап, нәтижелерді бағалаңыз.',
   continueBtn: 'Жалғастыру',
  },
  mzoStatisticalPainLevel: {
   title: 'Ауырсыну деңгейі',
   description1: 'Сіз соңғы рет ескертіңіз \
   сездің ауырғаныңды',
   description2: 'Деңгейде',
   description3: '0-ден 10-ға дейінгі шкала бойынша (0 - ауырсыну жоқ, 10 - шыдамайтын ауырсыну).',
   description4: 'Қазір бұл жердегі ауырсынуыңыз қандай деңгейде?',
   painItem1: 'Мойын',
   painItem2: 'Жамбас',
   painItem3: 'Иық',
   painItem4: 'Кеуде арқасы',
   painItem5: 'Тізе',
   painItem6: 'қол',
   painItem7: 'Бел',
   painItem8: 'Табан',
   continueBtn: 'Жалғастыру',
  },

mzoStatisticalStatus: {
   title: 'Сіздің жағдайыңыз',
   condition: 'Жалпы физикалық жағдайыңызды 0-ден 100%-ға дейінгі шкала бойынша бағалаңыз',
   energy: 'Орташа энергия деңгейіңізді 0-ден 100%-ға дейінгі шкала бойынша бағалаңыз',
   sleep: 'Ұйқыңыздың сапасын 0-ден 100%-ға дейінгі шкала бойынша бағалаңыз',
   continueBtn: 'Жалғастыру',
  },
  historyBirthday: {
   title: 'Туған күні',
   continueBtn: 'Жалғастыру'
  },
  historyDiagnosis: {
   title: 'Диагноз',
   subtitle: 'Сіздің диагнозыңыз қандай болды? (орнатылған болса)',
   continueBtn: 'Жалғастыру'
  },
  postureSide: {
   title1: 'Қай суретке көбірек ұқсайды',
   title2: 'Бүйірден қарағанда сіздің қалпыңыз?',
   error: 'Позаның түрін көрсетіңіз',
   type1: '1 түрі',
   type2: '2 түрі',
   type3: '3 түрі',
   continueBtn: 'Жалғастыру'
  },
  postureBack: {
   title1: 'Қай суретке көбірек ұқсайды',
   title2: 'Артынан қарағанда сіздің қалпыңыз?',
   error: 'Укажите тип осанки',
   type1: 'R түрі',
   type2: 'N түрі',
   type3: 'S түрі',
   endBtn: 'Аяқтау'
  },
  newClient: {
   history: 'Тарих',
   mobility: 'Ұтқырлық',
   posture: 'Дене қалпы',
  },
  registrationNewClient: {
   title: 'Жаңа клиент',
   error1: 'Қате деректер',
   error2: 'Бұл хат бұрыннан қолданыста',
   placeholder1: 'Электрондық пошта',
   placeholder2: 'Аты',
   placeholder3: 'Жөні',
   phonePlaceholder1: 'Елдің коды',
   phonePlaceholder2: 'Елді таңдаңыз',
   phonePlaceholder3: 'телефон нөмірі',
   phonePlaceholder4: 'Мысал :',
   continueBtn: 'Жалғастыру'
  },
  addReplaceExercise: {
   titleAdd: 'Жаттығу қосу',
   titleReplace: 'Жаттығуды ауыстыру',
   error: 'Жаттығуды таңдаңыз',
   example: 'Мысал көрсету',
   exerciseName: 'Жаттығуды таңдаңыз',
   searchPlaceholder: 'Іздеу...',
   seconds: 'Секунд',
   sets: 'Тәсіл',
   repeats: 'Қайталау',
   changeExercise: 'Басқа жаттығуды таңдаңыз',
   addBtn: 'Қосу'
  },
  closedWeek: {
   title: 'Апта жабылды',
   subtitle1: 'Жаттықтырушымен байланысыңыз және оған нәтижелеріңіз бен сезімдеріңіз туралы айтыңыз.',
   subtitle2: 'Осыдан кейін сіздің жаттықтырушы сізге келесі аптаға жаттығу бағдарламасын жасайды',
   subtitle3: 'Клиент өткен аптаны аяқтағаннан кейін жаңа апта ашылады',
  },
  completeDay: {
   title: 'Құтықтаймыз,',
   subtitle: 'Сіз күнді аяқтадыңыз',
   placeholder: 'Бүгінгі сезімдеріңізді сипаттаңыз',
   sendBtn1: 'Сақтау және үйге оралу',
   sendBtn2: 'Жабыңыз және үйге қайтыңыз',
  },
  deleteClient: {
   title: 'Клиентті жою',
   subtitle: 'Клиент дерекқорда тағы бір жыл сақталады. \
   Қазіргі уақытта қолдау сұрауы бойынша оны қайтаруға болады. \
   Содан кейін клиент біржола жойылады. \
   Клиентті шынымен жойғыңыз келе ме?',
   yesBtn: 'Иә',
   noBtn: 'Жоқ'
  },
  deleteExersice: {
   title: 'Жаттығуды жою',
   subtitle: 'Жаттығуды шынымен жойғыңыз келе ме?',
   yesBtn: 'Иә',
   noBtn: 'Жоқ'
  },
  editExersice: {
   title: 'Жаттығуды өңдеу',
   seconds: 'Секунд',
   sets: 'Тәсіл',
   repeats: 'Қайталау',
   continueBtn: 'Жалғастыру'
  },
  exampleExercise: {
   title: 'Жаттығудың сипаттамасы',
   video: 'Бейне',
   photo: 'Фото',
   startBtn: 'Бастау',
   stopBtn: 'Тоқта',
   resetBtn: 'қалпына келтіру',
   repeatsDescription: 'рет',
   setsDescription: 'Қайталау:',
  },
  firstLogin: {
   title: 'Қош келдіңіз',
   subtitle1: 'Сіз қолданбаға бірінші рет кірдіңіз.',
   subtitle2: 'Тіркелгіңізге құпия сөз жасаңыз.',
   changeErrorText: 'Құпия сөзді өзгерту кезінде қате пайда болды',
   changeSuccessText: 'Құпия сөз сәтті өзгертілді',
   passwordPlaceholder: 'Жаңа құпия сөз',
   repeatPasswordPlaceholder: 'Құпия сөзді қайталаңыз',
   saveBtn: 'Сақтау'
  },
  profileSettings: {
   title: 'Параметрлер',
   data: 'Деректер',
   password: 'Құпия сөз',
   error1: 'Қате деректер',
   error2: 'Құпия сөзді өзгерту қатесі',
   error3: 'Ағымдағы және жаңа құпия сөз сәйкестігі',
   dataSuccess: 'Деректер сәтті сақталды',
   passwordSuccess: 'Құпия сөз сәтті өзгертілді',
   placeholderEmail: 'Электрондық пошта',
   placeholderPhone1: 'Елдің коды',
   placeholderPhone2: 'Елді таңдаңыз',
   placeholderPhone3: 'Телефон нөмірі',
   placeholderPhone4: 'Мысал :',
   placeholderName: 'Аты',
   placeholderSurname: 'Жөні',
   placeholderOldPassword: 'Ескі Құпия сөз',
   placeholderNewPass: 'Жаңа құпия сөз',
   placeholderRepeatPass: 'Құпия сөзді қайталаңыз',
   saveBtn: 'Сақтау',
   resetWeeksBtn: 'Орындалу барысын қалпына келтіру',
  },
  resendCode: {
   title: 'Хат жіберу',
   subtitle1: 'Клиентке рұқсаты бар қайталанатын электрондық поштаны жіберіңіз -',
   subtitle2: 'Электрондық поштаға -',
   sendBtn: 'Жіберу'
  },
  resetWeeks: {
   title: 'Орындалу барысын қалпына келтіру',
   subtitle: 'Барлық орындалу барысын қалпына келтіргіңіз келетініне сенімдісіз бе?\
   Қалпына келтіргеннен кейін өткенді қайтару мүмкін емес екенін ескеріңіз.',
   yesBtn: 'Иә',
   noBtn: 'Жоқ',
  },
  statisticalCongratulations: {
   title: 'Құтықтаймыз,' ,
   subtitle1: 'Сіз жаттығуларыңызды орындадыңыз',
   subtitle2: 'екі рет!',
   subtitle3: 'үш рет!',
   description1: 'Біз шешім қабылдау үшін бірнеше сұрақтарға жауап беріңіз,',
   description2: 'Келесі қадам сіз үшін ең тиімді болады.',
   continueBtn: 'Жалғастыру',
  },
  statisticalResults: {
   title: 'Нәтиже',
   error: 'Барлық сұрақтарға жауап беріңіз',
   question1: 'Бағдарлама сізге көмектесіп жатыр деп ойлайсыз ба?',
   question2: 'Сіздің икемділігіңіз, ұтқырлығыңыз жақсарды ма?',
   question3: 'Денеңіз жақсарды ма?',
   question4: 'Сіздің денеңіздегі тепе-теңдік сезімі, күш-қуатыңыз жақсарды ма?',
   yesBtn: 'Иә',
   noBtn: 'Жоқ',
   continueBtn: 'Жалғастыру',
  },
  clientPageNav: {
   item1: 'Ескертпелер',
   item2: 'Жаттығу бағдарламалары',
   item3: 'Бағдарлама',
   item4: 'Фотосуреттер',
   item5: 'Статистика',
   item6: 'Клиент параметрлері',
   item7: 'Сауалнама',
   item8: 'Параметрлер',
   item9: 'Қосымша',
  },
  clientCard: {
   info1: 'Соңғы сабақ:',
   info2: 'Электрондық пошта:',
   info3: 'Телефон:',
   info4: 'Өткен апталар:',
   info5: '12-ден',
   info6: 'Өткен күндер:',
   info7: '7-ден',
   openBtn: 'Ашу',
  },
  clientChat: {
   title: 'Жаттықтырушыға жазыңыз',
   trainer: 'Сіздің жаттықтырушыңыз:',
   placeholder: 'Хабарлама жазу...',
  },
  cropImage: {
   placeholder: 'Жолды көрсету',
   turnDecription1: 'Дәрежелер бойынша бұру',
   turnDecription2: 'градус',
   saveBtn: 'Сақтау',
  },
  exerciseItem: {
   seconds: 'сек',
   sets: 'подход',
   reps: 'Қайталау',
   edit: 'Өзгерту',
   showAlternative: 'Ауыстырыңыз ',
   showExample: 'Сипаттама',
   delete: 'Жою'
  },
  photosItem: {
   compare: 'Салыстыру',
   delete: 'Жою',
   inComparison: 'Салыстыру үшін қосылды'
  },
  questionnaireBlock: {
   title: 'Сауалнама жауаптары',
   heightWeightTitle: 'Бой / Салмақ',
   heightWeightItem1: 'Бой',
   heightWeightItem2: 'Салмақ',
   workTitle: 'Мамандығыныз',
   workItem1: 'Кәсіпкер',
   workItem2: 'Үй шаруасындағы әйел',
   workItem3: 'Жүргізуші',
   workItem4: 'Фрилансер',
   workItem5: 'Студент',
   workItem6: 'Бағдарламашы',
   workItem7: 'Кеңсе қызметкері',
   workItem8: 'Мұғалім',
   workItem9: 'Зейнеткер',
   workItem10: 'Басқа мамандық',
   conditionTitle: 'Жалпы жағдай',
   conditionItem1: 'Сезім:',
   conditionItem2: 'Энергия:',
   conditionItem3: 'Үйқы:',
   painPlaceTitle: 'Ауырсынудың негізгі аймағы:',
   whenPainTitle: 'Сізді қашан мазалайды?:',
   whenPainItem1: 'Таңертең оянғаннан кейін',
   whenPainItem2: 'Күннің соңында',
   whenPainItem3: 'Жаттығудан кейін',
   whenPainItem4: 'Ұзақ отырған соң',
   whenPainItem5: 'Ауыр көтергеннен кейін',
   whenPainItem6: 'Әрқашан',
   whenPainItem7: 'Басқа уақыт:',
   diagnosisTitle: 'Диагноз',
   painTryTitle: 'Сіз қолданып көрген емдер',
   painTryItem1: 'Мануальная терапия',
   painTryItem2: 'Физиотерапия',
   painTryItem3: 'Ота',
   painTryItem4: 'Ауырсынуды басатын дәрі',
   painTryItem5: 'Иглотерапия',
   painTryItem6: 'Гирудотерапия',
   painTryItem7: 'ЛФК',
   painTryItem8: 'Йога, пилатесс',
   painTryItem9: 'Тартым',
   painTryItem10: 'Басқа емдеу түрлері',
   question1: 'Сізге тұру оңай ма',
   question2: 'Сізге отыру оңай ма',
   question3: 'Сізге еденнен тұру оңай ма?',
   complexitiesItem1: 'Оңай',
   complexitiesItem2: 'Жақсы',
   complexitiesItem3: 'қиын',
   complexitiesItem4: 'өте қиын',
   firstTest: '№1 функция сынағы',
   firstTestItem1: 'Тұрақтылық пен тепе-теңдік',
   firstTestItem2: 'Дене құлап немесе теңселіп жатыр',
   firstTestItem3: 'Жауап беруге қиналамын',
   secondTest: '№2 функция сынағы',
   secondTestItem1: 'Тұру оңай болды',
   secondTestItem2: 'Тұру қиындап кетті',
   secondTestItem3: 'Жауап беруге қиналамын',
   thirdTest: '№3 функция сынағы',
   thirdTestItem1: 'Сол жақта оңайырақ',
   thirdTestItem2: 'Бірдей оңай',
   thirdTestItem3: 'Оң жақта оңайырақ',
   thirdTestItem4: 'Бірдей қиын',
   thirdTestItem5: 'Жауап беруге қиналамын',
   postureTypeSide: 'Бүйірлік дененің түрі',
   postureTypeBack: 'Арқа дененің түрі ',
   postureTypeSideType1: '1 түрі',
   postureTypeSideType2: '2 түрі',
   postureTypeSideType3: '3 түрі',
   postureTypeBackType1: 'R түрі',
   postureTypeBackType2: 'N түрі',
   postureTypeBackType3: 'S түрі',
   notesTitle: 'Жаттығудан кейінгі жазбаларыңыз:',
   week: 'Апта:',
   day: 'Күн:',
  },
  regNav: {
   percents: '% Өтті',
   historyTitle: 'Тарих',
   historyItem1: 'Қош келдіңіз',
   historyItem2: 'Сіз туралы ақпарат',
   historyItem3: 'Сіздің жағдайыңыз',
   historyItem4: 'Ауырсыну туралы ақпарат',
   mobilityTitle: 'Ұтқырлық',
   mobilityItem1: 'Нұсқау',
   mobilityItem2: 'Сауалнама',
   mobilityItem3: 'Функционалдық тестілеу',
   postureTitle: 'Дене',
   postureItem1: 'Дене анықтау',
   postureItem2: 'Фотосуреттер',
   postureItem3: 'Финал',
  },
  trainerMessage: {
   placeholder: 'Хабарлама жазу...',
   sendBtn: 'Жауап',
  },
  weekCard: {
   completeTimes1: 'Аяқталды',
   completeTimes2: '/ 7 рет',
   completeTimes3: '/ 31 рет',
   complete: 'Толық аяқталды'
  },
  exercise: {
   backLink: 'Негізгі бетке оралу',
   day: 'Күн',
   exercise: 'Жаттығу',
   comment: 'Жаттықтырушының осы аптадағы пікірі',
   video: 'Бейне',
   photo: 'Фото',
   startBtn: 'Бастау',
   stopBtn: 'Тоқтау',
   resetBtn: 'Қалпына келтіру',
   repeats: 'Рет',
   sets: 'Қайталау:',
   backBth: 'Артқа қайту',
   continueBtn: 'Аяқтаңыз және келесіге өтіңіз',
   endBtn: 'Аяқтау'
  },
  faq: {
   title: 'Қосымша материалдар',
   tip: 'Сұрағыңызға жауап таппасаңыз, \
   содан кейін қолдау қызметіне хабарласыңыз \
   және біз сізге міндетті түрде көмектесеміз.',
   helpTitle: 'Біз сізге қалай көмектесе аламыз?'
  },
  clientIndex: {
   title1: 'Сіздің рұқсатыңыз аяқталады:',
   title2: 'в',
  },
  notes: {
   title: 'Ескертпелер',
   clearTitle: 'Жазбалар жоқ',
   clearSubtitle: 'Жаңа жазба жасау үшін осы блокты басыңыз',
   note: 'Ескертпелер №',
   createNote: 'Ескертпе қосу',
   editNote: 'Жазбаны өңдеу',
   placeholder: 'Ескерту мәтіні...',
   createBtn: 'Қосу',
   editBtn: 'Өңдеу',
  },
  photos: {
   backLink: 'Тұтынушы бетіне оралу',
   addPhotoBtn: 'Фото қосу',
   compare: 'Салыстырмалы фотосуреттерді жасыру / көрсету',
   emptyTitle: 'Фотосуреттер жоқ!',
   emptySubtitle: 'Осы блокты басу арқылы сіз жаңа фотосурет қоса аласыз',
   showLines: 'Жолдарды көрсету',
   clearBtn: 'Тазарту',
   compareDescription1: 'Салыстырғанда',
   compareDescription2: 'фото',
   compareBtn: 'Салыстыру'
  },
  statistics: {
   backLink: 'Артқа қайту',
   noData: 'Сіз жаттығу жасамадыңыз',
   unit: 'Жаттығу',
  },
  trainerWeek: {
   backLink: 'Артқа қайту',
   addIntsruction: 'Нұсқауларды қосу',
   placeholder1: 'Нұсқау...',
   openWeek: 'Клиент үшін бір апта ашық',
   exerciseTitle: 'Жаттығу',
   addExercise: '+ Жаттығуларды қосу',
   saveBtn: 'Өзгерістерді сақтау',
  },
  trainerClientIndex: {
   backLink: 'Тұтынушы бетіне оралу',
   notesTrainer: 'Жаттықтырушы жазбалары',
   notesClient: 'Клиент жазбалары',
   addNote: 'Ескертпе қосу',
   notesEmptyTrainerTitle: 'Жазбалар жоқ',
   notesEmptyTrainerSubtitle: 'Жаңа жазба жасау үшін осы блокты басыңыз',
   notesEmptyClientTitle: 'Жазбалар жоқ',
   notesEmptyClientSubtitle: 'Клиент өзіне әлі ешқандай ескертпе жасаған жоқ',
   note: 'Ескертпе №',
   addNoteTrainer: 'Ескертпе қосу',
   editNoteTrainer: 'Жазбаны өңдеу',
   placeholder: 'Ескерту мәтіні...',
   addNoteBtn: 'Қосу',
   editNoteBtn: 'Өзгерту'
  },
  trainerSettings: {
   backLink: 'Тұтынушы бетіне оралу',
   infoTitle: 'Негізгі ақпарат',
   error: 'Қате деректер',
   placeholderEmail: 'Электрондық пошта',
   placeholderPhone1: 'Елдің коды',
   placeholderPhone2: 'Елді таңдаңыз',
   placeholderPhone3: 'Телефон нөмірі',
   placeholderPhone4: 'Мысал :',
   placeholderName: 'Аты',
   placeholderSurname: 'Жөні',
   placeholderOldPassword: 'Ескі Құпия сөз',
   placeholderNewPass: 'Жаңа құпия сөз',
   placeholderRepeatPass: 'Құпия сөзді қайталаңыз',
   changeBtn: 'Клиент құпия сөзін өзгерту',
   additionalTitle: 'Қосымша',
   resendBtn: 'Қайталанатын хат жіберіңіз',
   error1: 'Электрондық поштаны жіберу қатесі.',
   success1: 'Пошта сәтті жіберілді',
   error2: 'Құпия сөзді өзгерту қатесі.',
   success2: 'Құпия сөз сәтті өзгертілді',
  },
  languageChange: {
   title: 'Тілді Өзгерту',
   changeBtn: 'Өзгерту',
   cancelBtn: 'Жою'
  },
  trainerIndex: {
   title: 'Клиенттер',
   placeholder: 'Клиент іздеуде...',
   addClientBtn: 'Клиентті қосу',
   error: 'Пайдаланушыны жою қатесі',
   success: 'Пайдаланушы сәтті жойылды'
  },
  trainerChat: {
   title: 'Хабарламалар',
   searchPlaceholder: 'Клиент іздеуде...',
   messageContent: 'Алғашқы хабарламаңызды жазыңыз',
   placeholder: 'Хабарлама жазуды бастау',
  },
  mainIndex: {
   title: 'Аккаунтқа кіру',
   placeholder1: 'Логин',
   placeholder2: 'құпия сөз',
   forgotPassword: 'Құпия сөзіңізді ұмыттыңыз ба?',
   signInBtn: 'Кіру',
   error1: 'Электрондық пошта немесе құпия сөз қатесі',
   error2: 'Жазылымыңыз аяқталды'
  },
  resetPassword: {
   backLink: 'Артқа қайту',
   title: 'Құпия сөзді қалпына келтіру',
   stepTitle1: 'Қадам',
   stepTitle2: '2-ден',
   step1_1: 'Құпия сөзіңізді ұмыттыңыз ба? Содан кейін қарапайым құпия сөзді қалпына келтіру пішінін пайдаланыңыз.',
   step1_2: 'Одан әрі әрекеттері бар хабарлама жіберілетін поштаны көрсету керек',
   step2_1: 'Соңғы қадам қалды!',
   step2_2: 'Енді сізге жаңа кіру құпия сөзін жасау керек.',
   step2_3: 'Сақтағаннан кейін сіз бірден есептік жазбаға түсесіз',
   placeholderEmail: 'Электрондық пошта',
   sendMailBtn: 'Хат жіберу',
   send1: 'Электрондық пошта сәтті жіберілді!',
   send2: 'Онда қосымша нұсқаулар бар',
   sendError: 'Құпия сөз 6 таңбадан көп болуы керек',
   placeholderNewPass: 'Жаңа құпия сөз',
   placeholderRepeatPass: 'Құпия сөзді қайталаңыз',
   saveBtn: 'Сақтау'
  },
}