export default {
   clientNav: {
     home: 'Главная',
     notes: 'Заметки',
     photos: 'Фотографии',
     statistic: 'Статистика',
     questionnaire: 'Опросник',
     faq: 'Дополнительные материалы',
     additional: 'Дополнительно',
     help: 'Помощь'
   },
   headerAccount: {
    settings: 'Настройки',
    language: 'Язык',
    exit: 'Выйти'
   },
   trainerNav: {
    clients: 'Клиенты',
    clientsMessages: 'Сообщения от клиентов'
   },
   historyIntroductions: {
    welcome: 'Добро пожаловать',
    historyTitle: '1. История',
    subtitle: "Чтобы подобрать для вас индивидуальную программу \
    тренировок, нам нужно узнать немного больше о \
    вас и вашей проблеме. Ответьте на вопросы о \
    вашей боли, способности двигаться и осанке. \
    Ваша программа упражнений будет доступна сразу, \
    после заполнения анкеты.",
    oferta1: 'Я ознакомлен(-а) и принимаю условия',
    oferta2: 'договора-оферты',
    oferta3: 'и',
    oferta4: 'политики конфиденциальности',
    oferta5: '.',
    continueBtn: 'Продолжить',
    startBtn: 'Начать'
   },
   historyPainInfo: {
    title: 'Информация о боли',
    subtitle: 'Укажите места боли',
    painPlace: 'Место боли',
    painPlaceShort: 'Где болит?',
    painPlaceItem1: 'Шея',
    painPlaceItem2: 'Бедро',
    painPlaceItem3: 'Плечи',
    painPlaceItem4: 'Грудной отдел спины',
    painPlaceItem5: 'Колено',
    painPlaceItem6: 'Кисти',
    painPlaceItem7: 'Поясница',
    painPlaceItem8: 'Стопа',
    painChoiceTitle: 'Выберите одно место, где болит сильнее всего',
    painNumberTitle: 'Как сильно болит от 0 до 10 ( 0 не болит, 10 - сильно болит )',
    painPlaceError: 'Укажите место боли',
    painNubmerError: 'Укажите силу боли',
    painTime: 'Как давно у вас эта боль?',
    painTimeShort: 'Как давно беспокоит эта боль?',
    painTimePlaceholder1: 'Лет',
    painTimePlaceholder2: 'Месяцев',
    painTimePlaceholder3: 'Дней',
    painTimeError: 'Укажите как давно у вас эта боль',
    painWhenTime: 'Укажите когда вас беспокоит боль',
    painWhenTimeShort: 'Когда вас больше всего беспокоит боль?',
    painWhenTimeError: 'Укажите когда возникает боль',
    painWhenTimePlaceholder1: 'Утром, после пробуждения',
    painWhenTimePlaceholder2: 'К концу дня',
    painWhenTimePlaceholder3: 'После тренировок',
    painWhenTimePlaceholder4: 'После долгого сидения',
    painWhenTimePlaceholder5: 'После поднятия тяжести',
    painWhenTimePlaceholder6: 'Всегда',
    painWhenTimePlaceholder7: 'Другое...',
    diagnosisTitle: 'Какой вам ставили диагноз? (если ставили)',
    painAdd: 'Болит где-то ещё? (Добавить еще одно место боли)',
    painAddShort: 'Болит где-то ещё?',
    painAddShortAnswer1: 'Да',
    painAddShortAnswer2: 'Нет',
    painDelete: 'Удалить дополнительное место боли',
    painAdditional: 'Есть ли еще боли, о которых вы хотели бы сообщить?',
    treatmentsTitle: 'Укажите способы лечения которые вы пробовали',
    treatmentsTitleShort: 'Какие способы лечения вы пробовали?',
    treatmentsPlaceholder1: 'Мануальная терапия',
    treatmentsPlaceholder2: 'Физиотерапия',
    treatmentsPlaceholder3: 'Операция',
    treatmentsPlaceholder4: 'Обезболивающее',
    treatmentsPlaceholder5: 'Иглотерапия',
    treatmentsPlaceholder6: 'Гирудотерапия',
    treatmentsPlaceholder7: 'ЛФК',
    treatmentsPlaceholder8: 'Йога, пилатесс',
    treatmentsPlaceholder9: 'Вытяжение',
    treatmentsPlaceholder10: 'Другое...',
    treatmentsError: 'Укажите какие способы лечения вы пробовали',
    continueBtn: 'Продолжить',
   },
   historyYourCondition: {
    title: 'Ваше состояние',
    subtitle: 'Теперь оцените свое состяние',
    conditionTitle: 'Общее состояние',
    conditionSubtitle: 'Оцените ваше общее физическое состояние по шкале от 0 до 100%',
    conditionPlaceholder: 'Опишите ваше общее физическое состояние',
    conditionError: 'Укажите ваше общее состояние',
    energyTitle: 'Энергия',
    energySubtitle: 'Оцените ваш средний уровень энергии по шкале от 0 до 100%',
    energyPlaceholder: 'Опишите ваш общий уровень энергии',
    energyError: 'Укажите ваше состояние энергии',
    sleepTitle: 'Сон',
    sleepSubtitle: 'Оцените ваше среднее качество сна по шкале от 0 до 100%',
    sleepPlaceholder: 'Опишите качество вашего сна',
    sleepError: 'Укажите ваше качество сна',
    continueBtn: 'Продолжить',
   },
   historyYourInfo: {
    title: 'Информация о вас',
    subtitle: 'Сейчас нам надо немного познакомиться. Укажите важную информацию о вас',
    sexTitle: 'Пол',
    sexItem1: 'Мужской',
    sexItem2: 'Женский',
    sexError: 'Выберите пол',
    birthTitle: 'Дата рождения',
    birthError: 'Укажите дату рождения',
    heightWeightTitle: 'Рост / Вес',
    heightWeightPlaceholder1: 'Рост',
    heightWeightPlaceholder2: 'Вес',
    heightWeightError: 'Укажите ваш рост и вес',
    workTitle: 'Чем вы занимаетесь?',
    workSubtitle: 'Это поможет нам понять насколько много вы двигаетесь',
    workItem1: 'Предприниматель',
    workItem2: 'Домохозяйка',
    workItem3: 'Водитель',
    workItem4: 'Фрилансер',
    workItem5: 'Студент',
    workItem6: 'Программист',
    workItem7: 'Офисный работник',
    workItem8: 'Преподаватель',
    workItem9: 'Пенсионер',
    workItem10: 'Другое...',
    workError: 'Укажите профессию',
    continueBtn: 'Продолжить',
   },
   mobilityIntroductions: {
    title: 'Инструкция',
    mobilityTitle: '2. Подвижность',
    subtitle: 'Далее, нам необходимо лучше понять ваши двигательные \
    способности и сделать вместе с вами несколько \
    простых функциональных тестов. Эти вопросы \
    помогут нам подобрать наиболее эффективные \
    упражнения для вас в вашей нынешней форме.',
    startBtn: 'Начать',
    continueBtn: 'Продолжить',
   },
   mobilityQuestion: {
    title: 'Опросник',
    subtitle: 'На этом шаге вам следует ответить на вопросы о ваших двигательных способностях',
    stayTitle: 'Легко ли вам стоять?',
    staySubtitle: 'Укажите свои ощущения',
    stayItem1: 'Легко',
    stayItem2: 'Нормально',
    stayItem3: 'Сложно',
    stayItem4: 'Очень сложно',
    stayError: 'Укажите легко ли вам стоять',
    sitTitle: 'Легко ли вам сидеть?',
    sitSubtitle: 'Укажите свои ощущения',
    sitItem1: 'Легко',
    sitItem2: 'Нормально',
    sitItem3: 'Сложно',
    sitItem4: 'Очень сложно',
    sitError: 'Укажите легко ли вам сидеть',
    standupTitle: 'Легко ли вам вставать с пола?',
    standupSubtitle: 'Укажите свои ощущения',
    standupItem1: 'Легко',
    standupItem2: 'Нормально',
    standupItem3: 'Сложно',
    standupItem4: 'Очень сложно',
    standupError: 'Укажите легко ли вам вставать с пола',
    continueBtn: 'Продолжить',
   },
   mobilityTest: {
    title: 'Опросник',
    subtitle: 'На этом шаге вам следует ответить на вопросы о ваших двигательных способностях',
    firstTestTitle: 'Функциональный тест #1',
    firstTestSubtitle: 'Укажите свои ощущения',
    firstTestQuestionDescription: 'Встаньте без обуви. \
    Поставьте стопы вместе. \
    Расслабьтесь и не позируйте. Закройте глаза.',
    firstTestQuestionDescriptionAdditional: 'Какие у вас ощущения?',
    firstTestQuestionItem1: 'Стабильность и баланс',
    firstTestQuestionItem2: 'Тело падает или покачивается',
    firstTestQuestionItem3: 'Затрудняюсь ответить',
    firstTestQuestionError: 'Укажите легко ли вам стоять',
    secondTestTitle: 'Функциональный тест #2',
    secondTestSubtitle: 'Укажите свои ощущения',
    secondTestQuestionDescription: 'Оставайтесь в положении стоя, стопы вместе. \
    Скрестите пальцы рук за головой. \
    Максимально отведите локти назад расширяя грудную клетку. \
    Закройте глаза. Изменились ли ваши ощущения?',
    secondTestQuestionItem1: 'Стало легче стоять',
    secondTestQuestionItem2: 'Стало тяжелее стоять',
    secondTestQuestionItem3: 'Затрудняюсь ответить',
    secondTestQuestionError: 'Укажите легко ли вам сидеть',
    trirdTestTitle: 'Функциональный тест #3',
    trirdTestSubtitle: 'Укажите свои ощущения',
    trirdTestQuestionDescription: 'Встаньте без обуви. Поднимите одну ногу. \
    Прислушайтесь к своим ощущениям. Поменяйте ноги и повторите.  \
    Какие были у вас ощущения? Легко ли было стоять на каждой из ног?',
    trirdTestQuestionItem1: 'На левой легче',
    trirdTestQuestionItem2: 'Одинаково легко',
    trirdTestQuestionItem3: 'На правой легче',
    trirdTestQuestionItem4: 'Одинаково тяжело',
    trirdTestQuestionItem5: 'Затрудняюсь ответить',
    trirdTestQuestionError: 'Укажите легко ли вам вставать с пола',
    continueBtn: 'Продолжить',
   },
   postureFinal: {
    title: 'Финал',
    subtitle: 'Поздравляем с успешным завершением опросника. Если вы уверены в введенной информации, то нажмите кнопку "Завершить". \
    Учтите, что после изменить параметры будет нельзя.',
    endBtn: 'Завершить'
   },
   postureIntroductions: {
    title: 'Определение осанки',
    postureTitle: '3. Осанка',
    error: 'Укажите тип осанки',
    subtitle: 'Посмотрите на фото вашей осанки сбоку. Обратите внимание на положение таза. \
    Какой из приведенных ниже типов осанки больше всего напоминает ваше тело? \
    Выберите наиболее похожий вариант, даже если сходство не 100%, не зацикливайтесь на этом вопросе',
    type1: 'Тип 1',
    type2: 'Тип 2',
    type3: 'Тип 3',
    sideError: 'Укажите тип осанки сбоку',
    type1Description: 'Тип 1: Таз наклонен вперед. В пояснице ярко выраженный прогиб (лордоз). Живот округлый.',
    type2Description: 'Тип 2: Таз наклонен назад. Поясница довольно плоская. Позвоночник больше напоминает букву С, а не S. Верхняя часть тела сутулая.',
    type3Description: 'Тип 3: Таз заметно выдвинут вперед относительно ног и плеч. Тело напоминает дугу или скобку  “)”',
    scoliosisTitle: 'У вас есть сколиоз?',
    scoliosisItem1: 'Да',
    scoliosisItem2: 'Нет',
    additionalQuestionDescription1: 'Встаньте без обуви. Расслабьтесь, не позируйте.',
    additionalQuestionDescription2: 'Посмотрите на свое тело вниз и в отражении в зеркале.',
    additionalQuestionDescription3: 'Видите ли вы небольшой разворот в плечах или ногах? Может быть одна рука, нога или бедро немного перед другой?',
    additionalQuestionDescription4: 'Обратите внимание на положение стоп относительно друг друга? На одной ли они линии?',
    additionalQuestionDescription5: 'Посмотрите на руки? Одинаково ли расположены кисти?',
    spreadsTitle: 'Видите ли вы признаки разворотов в теле?',
    spreadsItem1: 'Да',
    spreadsItem2: 'Нет',
    startBtn: 'Начать',
    continueBtn: 'Продолжить',
   },
   posturePhotos: {
    title: 'Фотографии',
    photosTitle: 'Загрузите ваши фотографии',
    photosTitleShort: 'Загрузите фотографии осанки',
    photosSubtitle: 'При загрузке фото поставьте линию осанки ровно по центру',
    showLinesName: 'Показывать линии',
    addPhoto: 'Добавить фото',
    continueBtn: 'Продолжить',
   },
   completeReg: {
    title: 'Завершение',
    subtitle: 'Идет создание вашей уникальной программы упражнений!'
   },
   mzoStatisticalAllDone: {
    title: 'Все готово!',
    subtitle1: 'Спасибо за ваши ответы!',
    subtitle2: 'Мы продолжаем адаптировать программу упражнений под ваше состояние',
    continueBtn: 'Продолжить',
   },
   mzoStatisticalCongratulations: {
    title: 'Поздравляем,',
    subtitle1: 'Вы закончили',
    subtitle2: 'неделю программы МЗО!',
    description: 'Сделайте паузу и оцените свои результаты.',
    continueBtn: 'Продолжить',
   },
   mzoStatisticalPainLevel: {
    title: 'Уровень боли',
    description1: 'В прошлый раз вы отметили, \
    что у вас была боль в',
    description2: 'на уровне',
    description3: 'по шкале от 0 до 10 (0 - не болит, 10 - болит невыносимо).',
    description4: 'На каком уровне сейчас ваша боль в этом месте?',
    painItem1: 'Шея',
    painItem2: 'Бедро',
    painItem3: 'Плечи',
    painItem4: 'Грудной отдел спины',
    painItem5: 'Колено',
    painItem6: 'Кисти',
    painItem7: 'Поясница',
    painItem8: 'Стопа',
    continueBtn: 'Продолжить',
   },
   mzoStatisticalStatus: {
    title: 'Состояние',
    condition: 'Оцените ваше общее физическое состояние по шкале от 0 до 100%',
    energy: 'Оцените ваш средний уровень энергии по шкале от 0 до 100%',
    sleep: 'Оцените качество вашего сна по шкале от 0 до 100%',
    continueBtn: 'Продолжить',
   },
   historyBirthday: {
    title: 'Дата рождения',
    continueBtn: 'Продолжить'
   },
   historyDiagnosis: {
    title: 'Диагноз',
    subtitle: 'Какой вам ставили диагноз? (если ставили)',
    continueBtn: 'Продолжить'
   },
   postureSide: {
    title1: 'На какое изображение больше всего похожа',
    title2: 'ваша осанка при виде сбоку?',
    error: 'Укажите тип осанки',
    type1: 'Тип 1',
    type2: 'Тип 2',
    type3: 'Тип 3',
    continueBtn: 'Продолжить'
   },
   postureBack: {
    title1: 'На какое изображение больше всего похожа',
    title2: 'ваша осанка при виде сзади?',
    error: 'Укажите тип осанки',
    type1: 'Тип R',
    type2: 'Тип N',
    type3: 'Тип S',
    endBtn: 'Завершить'
   },
   newClient: {
    history: 'История',
    mobility: 'Подвижность',
    posture: 'Осанка',
   },
   registrationNewClient: {
    title: 'Новый клиент',
    error1: 'Неправильные данные',
    error2: 'Эта почта уже используется',
    placeholder1: 'Email',
    placeholder2: 'Имя',
    placeholder3: 'Фамилия',
    phonePlaceholder1: 'Код страны',
    phonePlaceholder2: 'Выберите страну',
    phonePlaceholder3: 'Номер телефона',
    phonePlaceholder4: 'Пример :',
    continueBtn: 'Продолжить'
   },
   addReplaceExercise: {
    titleAdd: 'Добавить упражнение',
    titleReplace: 'Заменить упражнение',
    error: 'Выберите упражнение',
    example: 'Показать пример',
    exerciseName: 'Выберите упражнение',
    searchPlaceholder: 'Поиск...',
    seconds: 'Секунд',
    sets: 'Подхода (ов)',
    repeats: 'Повторений',
    changeExercise: 'Выбрать другое упражнение',
    addBtn: 'Добавить'
   },
   closedWeek: {
    title: 'Неделя закрыта',
    subtitle1: 'Свяжитесь с вашим тренером и расскажите ему/ей о ваших результатах и ощущениях.',
    subtitle2: 'После этого ваш тренер составит для вас программу упражнений на следующую неделю',
    subtitle3: 'Новая неделя откроется после полного завершения предыдущей недели клиентом',
   },
   completeDay: {
    title: 'Поздравляем,',
    subtitle: 'Вы завершили день',
    placeholder: 'Опишите свои ощущения сегодня',
    sendBtn1: 'Сохранить и вернуться на главную',
    sendBtn2: 'Закрыть и вернуться на главную',
   },
   deleteClient: {
    title: 'Удаление клиента',
    subtitle: 'Клиент будет храниться в базе еще в течении года. \
    В это время его можно вернуть по запросу в поддержку. \
    Далее клиент будет безвозвратно удален. \
    Вы уверены, что хотите удалить клиента?',
    yesBtn: 'Да',
    noBtn: 'Нет'
   },
   deleteExersice: {
    title: 'Удаление упражнения',
    subtitle: 'Вы уверены, что хотите удалить упражнение?',
    yesBtn: 'Да',
    noBtn: 'Нет'
   },
   editExersice: {
    title: 'Редактировать упражнение',
    seconds: 'Секунд',
    sets: 'Подхода (ов)',
    repeats: 'Повторений',
    continueBtn: 'Продолжить'
   },
   exampleExercise: {
    title: 'Описание упражнения',
    video: 'Видео',
    photo: 'Фото',
    startBtn: 'Начать',
    stopBtn: 'Стоп',
    resetBtn: 'Сброс',
    repeatsDescription: 'раз(а)',
    setsDescription: 'Повторений:',
   },
   firstLogin: {
    title: 'Добро пожаловать',
    subtitle1: 'Вы совершили первый вход в приложение.',
    subtitle2: 'Пожалуйста, создайте пароль для вашей учетной записи.',
    changeErrorText: 'Ошибка при смене пароля',
    changeSuccessText: 'Пароль успешно изменен',
    passwordPlaceholder: 'Новый пароль',
    repeatPasswordPlaceholder: 'Повторите пароль',
    saveBtn: 'Сохранить'
   },
   profileSettings: {
    title: 'Настройки',
    data: 'Данные',
    password: 'Пароль',
    error1: 'Неправильные данные',
    error2: 'Ошибка при смене пароля',
    error3: 'Текущий и новый пароль совпадают',
    dataSuccess: 'Данные успешно сохранены',
    passwordSuccess: 'Пароль успешно изменен',
    placeholderEmail: 'Email',
    placeholderPhone1: 'Код страны',
    placeholderPhone2: 'Выберите страну',
    placeholderPhone3: 'Номер телефона',
    placeholderPhone4: 'Пример :',
    placeholderName: 'Имя',
    placeholderSurname: 'Фамилия',
    placeholderOldPassword: 'Старый пароль',
    placeholderNewPass: 'Новый пароль',
    placeholderRepeatPass: 'Повторите пароль',
    saveBtn: 'Сохранить',
    resetWeeksBtn: 'Сбросить прогресс',
   },
   resendCode: {
    title: 'Отправить письмо',
    subtitle1: 'Отправить повторное письмо с доступом клиенту -',
    subtitle2: 'на почту -',
    sendBtn: 'Отправить'
   },
   resetWeeks: {
    title: 'Сброс прогресса',
    subtitle: 'Вы уверены, что хотите сбросить весь прогресс?\
    Учтите, что после сброса вернуть пройденное невозможно.',
    yesBtn: 'Да',
    noBtn: 'Нет',
   },
   statisticalCongratulations: {
    title: 'Поздравляем,' ,
    subtitle1: 'Вы сделали свои упражнения',
    subtitle2: 'раз!',
    subtitle3: 'раза!',
    description1: 'Пожалуйста, ответьте на несколько вопросов, чтобы мы могли решить,',
    description2: 'какой следующий шаг будет для вас наиболее эффективным.',
    continueBtn: 'Продолжить',
   },
   statisticalResults: {
    title: 'Результаты',
    error: 'Пожалуйста ответьте на все вопросы',
    question1: 'Чувствуете ли вы, что программа помогает вам?',
    question2: 'Улучшилась ли ваша гибкость, подвижность?',
    question3: 'Улучшились ли ваша осанка?',
    question4: 'Улучшилось ли ваше чувство баланса, силы в теле?',
    yesBtn: 'Да',
    noBtn: 'Нет',
    continueBtn: 'Продолжить',
   },
   clientPageNav: {
    item1: 'Заметки',
    item2: 'Программы упражнений',
    item3: 'Программа',
    item4: 'Фотографии',
    item5: 'Статистика',
    item6: 'Настройки клиента',
    item7: 'Опросник',
    item8: 'Настройки',
    item9: 'Дополнительно',
   },
   clientCard: {
    info1: 'Последние занятие:',
    info2: 'Email:',
    info3: 'Телефон:',
    info4: 'Пройдено недель:',
    info9: 'Пройдено месяцев:',
    info5: 'из 12',
    info10: 'из 15',
    info6: 'Пройдено дней:',
    info7: 'из 7',
    info8: 'из 31',
    openBtn: 'Открыть',
   },
   clientChat: {
    title: 'Написать тренеру',
    trainer: 'Ваш тренер:',
    placeholder: 'Написать сообщение...',
   },
   cropImage: {
    placeholder: 'Показать линию',
    turnDecription1: 'Повернуть на',
    turnDecription2: 'градусов',
    saveBtn: 'Сохранить',
   },
   exerciseItem: {
    seconds: 'сек',
    sets: 'подхода',
    reps: 'повторений',
    edit: 'Изменить',
    showAlternative: 'Заменить',
    showExample: 'Описание',
    delete: 'Удалить'
   },
   photosItem: {
    compare: 'Сравнить',
    delete: 'Удалить',
    inComparison: 'Добавлено в сравнение'
   },
   questionnaireBlock: {
    backLink: 'Вернуться на страницу клиентов',
    title: 'Ответы на опросник',
    birthdayTitle: 'Дата рождения',
    heightWeightTitle: 'Рост / Вес',
    heightWeightItem1: 'Рост',
    heightWeightItem2: 'Вес',
    workTitle: 'Профессия',
    workItem1: 'Предприниматель',
    workItem2: 'Домохозяйка',
    workItem3: 'Водитель',
    workItem4: 'Фрилансер',
    workItem5: 'Студент',
    workItem6: 'Программист',
    workItem7: 'Офисный работник',
    workItem8: 'Преподаватель',
    workItem9: 'Пенсионер',
    workItem10: 'Другая профессия',
    conditionTitle: 'Общее состояние',
    conditionItem1: 'Самочувствие:',
    conditionItem2: 'Энергия:',
    conditionItem3: 'Сон:',
    painPlaceTitle: 'Основной участок боли:',
    whenPainTitle: 'Когда беспокоит:',
    whenPainItem1: 'Утром, после пробуждения',
    whenPainItem2: 'К концу дня',
    whenPainItem3: 'После тренировок',
    whenPainItem4: 'После долгого сидения',
    whenPainItem5: 'После поднятия тяжести',
    whenPainItem6: 'Всегда',
    whenPainItem7: 'Другое время:',
    diagnosisTitle: 'Диагноз',
    painTryTitle: 'Способы лечения, которые вы пробовали',
    painTryItem1: 'Мануальная терапия',
    painTryItem2: 'Физиотерапия',
    painTryItem3: 'Операция',
    painTryItem4: 'Обезболивающее',
    painTryItem5: 'Иглотерапия',
    painTryItem6: 'Гирудотерапия',
    painTryItem7: 'ЛФК',
    painTryItem8: 'Йога, пилатесс',
    painTryItem9: 'Вытяжение',
    painTryItem10: 'Другие способы лечения',
    question1: 'Легко ли вам стоять',
    question2: 'Легко ли вам сидеть',
    question3: 'Легко ли вам вставать с пола',
    complexitiesItem1: 'Легко',
    complexitiesItem2: 'Нормально',
    complexitiesItem3: 'Сложно',
    complexitiesItem4: 'Очень сложно',
    firstTest: 'Функциональный тест #1',
    firstTestItem1: 'Стабильность и баланс',
    firstTestItem2: 'Тело падает или покачивается',
    firstTestItem3: 'Затрудняюсь ответить',
    secondTest: 'Функциональный тест #2',
    secondTestItem1: 'Стало легче стоять',
    secondTestItem2: 'Стало тяжелее стоять',
    secondTestItem3: 'Затрудняюсь ответить',
    thirdTest: 'Функциональный тест #3',
    thirdTestItem1: 'На левой легче',
    thirdTestItem2: 'Одинаково легко',
    thirdTestItem3: 'На правой легче',
    thirdTestItem4: 'Одинаково тяжело',
    thirdTestItem5: 'Затрудняюсь ответить',
    postureTypeSide: 'Тип осанки сбоку',
    postureTypeBack: 'Тип осанки сзади',
    postureTypeSideType1: 'Тип 1',
    postureTypeSideType2: 'Тип 2',
    postureTypeSideType3: 'Тип 3',
    postureTypeBackType1: 'Тип R',
    postureTypeBackType2: 'Тип N',
    postureTypeBackType3: 'Тип S',
    notesTitle: 'Ваши записи после упражнений:',
    week: 'Неделя:',
    day: 'день:',
   },
   regNav: {
    percents: '% Пройдено',
    historyTitle: 'История',
    historyItem1: 'Добро пожаловать',
    historyItem2: 'Информация о вас',
    historyItem3: 'Ваше состояние',
    historyItem4: 'Информация о боли',
    mobilityTitle: 'Подвижность',
    mobilityItem1: 'Инструкция',
    mobilityItem2: 'Опросник',
    mobilityItem3: 'Функциональное тестирование',
    postureTitle: 'Осанка',
    postureItem1: 'Определение осанки',
    postureItem2: 'Фотографии',
    postureItem3: 'Финал',
   },
   trainerMessage: {
    placeholder: 'Написать сообщение...',
    sendBtn: 'Ответить',
   },
   weekCard: {
    completeTimes1: 'Завершено',
    completeTimes2: '/ 7 раз',
    completeTimes3: '/ 31 раз',
    complete: 'Полностью завершена'
   },
   exercise: {
    backLink: 'Вернуться на главную страницу',
    day: 'День',
    exercise: 'Упражнение',
    comment: 'Комментарий тренера для этой недели',
    video: 'Видео',
    photo: 'Фото',
    startBtn: 'Начать',
    stopBtn: 'Стоп',
    resetBtn: 'Сброс',
    repeats: 'Подходов:',
    sets: 'Повторений:',
    backBth: 'Вернуться назад',
    continueBtn: 'Завершить и перейти к следующему',
    endBtn: 'Завершить'
   },
   faq: {
    title: 'Дополнительные материалы',
    tip: 'Если вы не нашли ответ на свой вопрос, \
    тогда обратитесь в службу поддержки \
    и мы обязательно поможем вам.',
    helpTitle: 'Чем вам помочь?'
   },
   clientIndex: {
    title1: 'Ваш доступ закончится:',
    title2: 'в',
   },
   notes: {
    title: 'Заметки',
    clearTitle: 'Нет заметок',
    clearSubtitle: 'Нажмите на этот блок чтобы создать новую заметку',
    note: 'Заметка №',
    createNote: 'Добавить заметку',
    editNote: 'Изменить заметку',
    placeholder: 'Текст заметки...',
    createBtn: 'Добавить',
    editBtn: 'Изменить',
   },
   photos: {
    backLink: 'Вернуться на страницу клиентов',
    addPhotoBtn: 'Добавить фото',
    compare: 'Скрыть / Показать фото в сравнении',
    emptyTitle: 'Нет фотографий!',
    emptySubtitle: 'При нажатии на этот блок вы сможете добавить новую фотограцию',
    showLines: 'Показывать линии',
    clearBtn: 'Очистить',
    compareDescription1: 'В сравнении',
    compareDescription2: 'фото',
    compareBtn: 'Сравнить'
   },
   statistics: {
    backLink: 'Вернуться назад',
    backLinkTrainer: 'Вернуться на страницу клиентов',
    noData: 'Вы не выполняли упражнения',
    unit: 'упражнений',
   },
   trainerWeek: {
    backLink: 'Вернуться назад',
    addIntsruction: 'Добавить инструкцию',
    placeholder1: 'Инструкция...',
    openWeek: 'Открыть неделю для клиента',
    exerciseTitle: 'Упражнения',
    addExercise: '+ Добавить упражнение',
    saveBtn: 'Сохранить изменения',
   },
   trainerClientIndex: {
    backLink: 'Вернуться на страницу клиентов',
    notesTrainer: 'Заметки тренера',
    notesClient: 'Заметки клиента',
    addNote: 'Добавить заметку',
    notesEmptyTrainerTitle: 'Нет заметок',
    notesEmptyTrainerSubtitle: 'Нажмите на этот блок чтобы создать новую заметку',
    notesEmptyClientTitle: 'Нет заметок',
    notesEmptyClientSubtitle: 'Клиент пока не делал себе заметок',
    note: 'Заметка №',
    addNoteTrainer: 'Добавить заметку',
    editNoteTrainer: 'Изменить заметку',
    placeholder: 'Текст заметки...',
    addNoteBtn: 'Добавить',
    editNoteBtn: 'Изменить'
   },
   trainerSettings: {
    backLink: 'Вернуться на страницу клиентов',
    infoTitle: 'Главная информация',
    error: 'Неправильные данные',
    placeholderEmail: 'Email',
    placeholderPhone1: 'Код страны',
    placeholderPhone2: 'Выберите страну',
    placeholderPhone3: 'Номер телефона',
    placeholderPhone4: 'Пример :',
    placeholderName: 'Имя',
    placeholderSurname: 'Фамилия',
    placeholderOldPassword: 'Старый пароль',
    placeholderNewPass: 'Новый пароль',
    placeholderRepeatPass: 'Повторите пароль',
    changeBtn: 'Изменить пароль клиента',
    saveChangeBtn: 'Сохранить изменения',
    additionalTitle: 'Дополнительно',
    resendBtn: 'Отправить поторное письмо',
    error1: 'Ошибка отправки письма.',
    success1: 'Письмо успешно отправлено',
    error2: 'Ошибка смены пароля.',
    success2: 'Пароль успешно изменен',
   },
   languageChange: {
    title: 'Смена языка',
    changeBtn: 'Изменить',
    cancelBtn: 'Отмена'
   },
   trainerIndex: {
    title: 'Клиенты',
    placeholder: 'Поиск клиента...',
    addClientBtn: 'Добавить клиента',
    error: 'Ошибка удаления пользователя',
    success: 'Пользователь успешно удален'
   },
   trainerChat: {
    title: 'Сообщения',
    searchPlaceholder: 'Поиск клиента...',
    messageContent: 'Напишите первое сообщение',
    placeholder: 'Начните писать сообщение',
   },
   mainIndex: {
    title: 'Войдите в аккаунт',
    placeholder1: 'Логин',
    placeholder2: 'Пароль',
    forgotPassword: 'Забыли пароль?',
    signInBtn: 'Войти',
    error1: 'Ошибка email или пароля',
    error2: 'Ваша подписка закончилась'
   },
   resetPassword: {
    backLink: 'Вернуться назад',
    title: 'Восстановление пароля',
    stepTitle1: 'Шаг',
    stepTitle2: 'из 2',
    step1_1: 'Забыли пароль? Тогда воспользуйтесь простой формой восстановления пароля.',
    step1_2: 'Вам следует указать почту на которую придет сообщение с дальнейшими действиями',
    step2_1: 'Оставлся последний шаг!',
    step2_2: 'Теперь вам надо придумать новый пароль для входа.',
    step2_3: 'После сохранения вы сразу попадете в аккаунт',
    placeholderEmail: 'Email',
    sendMailBtn: 'Отправить письмо',
    send1: 'Письмо успешно отправлено на почту!',
    send2: 'В нем находятся дальнейшая инструкция',
    sendError: 'Пароль должен быть больше 6 знаков',
    placeholderNewPass: 'Новый пароль',
    placeholderRepeatPass: 'Повторите пароль',
    saveBtn: 'Сохранить'
   },
 }